### ISSUE TITLE
Change home url for the app

### ISSUE THREAD

**Issue by krritik** [krritik/nest4guest#2]
Currently to open the app, we have to open the link '127.0.0.1:8080/home' or in heroku it is 'https://nest4guest.herokuapp.com/home'

Change the relative url for home. So that it opens in 'https://nest4guest.herokuapp.com/'

**Comment by sid779** [comment]
Hey, I would like to work on it too. Could you please assign it to me.

**Comment by mac912** [comment]
Hey, I would like to work on it too
