### ISSUE TITLE
Create a staff-login page

### ISSUE THREAD

**Issue by krritik** [krritik/nest4guest#22]
Currently, staff-login is the default admin page, which makes it look different from the rest of the website. So, create a staff-login page for it similar to the layout of the website.
![Screenshot from 2019-12-09 14-38-37](https://user-images.githubusercontent.com/32814075/70422362-a3dd7080-1a91-11ea-8ce1-cfbb80f6ce58.png)
the current staff login page
![Screenshot from 2019-12-09 14-38-46](https://user-images.githubusercontent.com/32814075/70422383-ac35ab80-1a91-11ea-8461-b9c42ace3b43.png)
make it similar to this.

**Comment by rrohit2901** [comment]
Can I work on this issue??

**Comment by krritik** [comment]
Sue, you can take this issue

**Comment by Sahilbabani** [comment]
changed layout of staff pages 
pr #26
