### ISSUE TITLE
Add error message for superuser or staff in visitor's login

### ISSUE THREAD

**Issue by Rits1272** [krritik/nest4guest#23]
When a superuser or staff tries to login in visitor's login page, he is simply redirected to the index page without any message that the login form is only for visitors. I also have changed little bit styling of the error message

**Comment by Rits1272** [comment]
PR : #24

**Comment by krritik** [comment]
write a small title and use description to explain it.

**Comment by Rits1272** [comment]
Done @krritik!

**Comment by Rits1272** [comment]
My new pr #24
