### ISSUE TITLE
Add static files like images, gifs

### ISSUE THREAD

**Issue by krritik** [krritik/nest4guest#3]
Currently the website is very simple and it does not have any images or animations.
Add few like Guest House photos, some animations to make website more appealing

**Comment by mac912** [comment]
hey, I would like to work on it please assign it to me

**Comment by krritik** [comment]
One can take an issue, assigning is not important (so others can also work on that)
**Note:** Read once contribution details which I added in the readme.

**Comment by ritik5049** [comment]
Hey, I would like to work on this issue.

**Comment by krritik** [comment]
I do not think this can be done separately to the frontend. So I will be closing this issue.
