### ISSUE TITLE
URL for roomdetails is not working .

### ISSUE THREAD

**Issue by Suchana34** [krritik/nest4guest#34]
The /roomdetails/  URL is getting some error in the function named roomdetails and redirecting to the profile page (index).

**Comment by Rits1272** [comment]
PR : #35

**Comment by Suchana34** [comment]
Yes, it works now.

**Comment by krritik** [comment]
What was the error? I did not get it.

**Comment by Suchana34** [comment]
The links to the URL /roomdetails were not directed to the room details page. Instead the index page showed up.
