### ISSUE TITLE
Incorrect title of home page

### ISSUE THREAD

**Issue by krritik** [krritik/nest4guest#4]
Currently the html titile of home page is "CSS Website Layout" change it to something like "Home-Nest4Guest"

**Comment by sid779** [comment]
Hey, I would like to work on it. Could you please assign it to me.

**Comment by mac912** [comment]
I would like to work on it.

**Comment by iharshit009** [comment]
@krritik  #19 refers to this PR.

**Comment by krritik** [comment]
done
