### ISSUE TITLE
About Page Does Not Exist

### ISSUE THREAD

**Issue by parjanyaacoder** [krritik/nest4guest#7]
The About Page of the website does not exist.Also after creating a page for About it needs to be linked to the main home page

**Comment by promaroy** [comment]
Can I work on this?

**Comment by krritik** [comment]
You can take this issue and work on this.

**Comment by promaroy** [comment]
Can you please suggest the content or details the about page may contain?

**Comment by krritik** [comment]
![Screenshot from 2019-12-08 14-06-22](https://user-images.githubusercontent.com/32814075/70386861-f7818880-19c3-11ea-8278-6ee9643a429c.png)
You can write something like this. Currently, there are no pictures, so you add them( any picture from google) in static files, Number and name of guesthouses can be used from the database. If you think, you need something that is not in the database, you can create columns too. 
If you have any queries or you want to do something new, let me know.

**Comment by krritik** [comment]
solved using PR #32
