### ISSUE TITLE
Add a payment mode

### ISSUE THREAD

**Issue by krritik** [krritik/nest4guest#9]
Currently, there is no payment mode, while making a reservation or on cancellation, it just updates the details about payment in the database. So we can integrate a payment mode to make it more realistic.

**Comment by Rits1272** [comment]
Can I work on this issue?

**Comment by krritik** [comment]
One can take an issue but others can also work on that.

**Comment by Rits1272** [comment]
My PR : #18

**Comment by Rits1272** [comment]
Here is my PR : #20
